# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.IntegerField()),
                ('img', models.ImageField(upload_to='brandimg')),
                ('title', models.CharField(default=None, max_length=100)),
                ('desciption', models.CharField(default=None, max_length=100)),
                ('trackid', models.IntegerField()),
            ],
            options={
                'db_table': 'brandimg',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('img', models.ImageField(upload_to='goodsimg')),
                ('smallImg', models.ImageField(upload_to='smallImg')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('oldprice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sales', models.IntegerField()),
                ('store', models.IntegerField()),
                ('bg', models.ImageField(upload_to='bg')),
                ('trackid', models.IntegerField()),
            ],
            options={
                'db_table': 'goods',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('tel', models.CharField(max_length=20, unique=True)),
                ('img', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='lbimg')),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.IntegerField()),
            ],
            options={
                'db_table': 'wheelimg',
            },
        ),
    ]
