# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=20)),
                ('img2', models.CharField(default='1', max_length=100)),
            ],
            options={
                'db_table': 'temp_wheel',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('tel', models.CharField(max_length=20, unique=True)),
                ('img', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trackid', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='lbimg')),
            ],
            options={
                'db_table': 'mgj_wheel',
            },
        ),
    ]
