# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='img2',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
