# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-12 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_order_ordergoods'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ordergoods',
            table='ordergoods',
        ),
    ]
